version: "3.9"

services:
  db:
    image: postgres
    container_name: psql_db

    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: django_rest_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  react-app:
    container_name: react_web_app
    build: '../../front/mfi_mountain_peaks'
    ports:
      - "3000:3000"
volumes:
  db_volume:
    external: true