# Generated by Django 4.0.4 on 2022-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mountain_peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('location', models.CharField(max_length=240, verbose_name='Location')),
                ('latitude', models.IntegerField(max_length=240, verbose_name='Latitude')),
                ('longitude', models.IntegerField(max_length=240, verbose_name='Longitude')),
                ('altitude', models.IntegerField(max_length=240, verbose_name='Altitude')),
            ],
        ),
    ]
