# Generated by Django 4.0.4 on 2022-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mountain_peak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain_peak',
            name='latitude',
            field=models.CharField(max_length=240, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='mountain_peak',
            name='longitude',
            field=models.CharField(max_length=240, verbose_name='Longitude'),
        ),
    ]
